# Generated by Django 4.2.3 on 2024-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_tarjeta_fecha_expiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_expiracion',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='balance',
            field=models.IntegerField(default=1000000, max_length=15),
            preserve_default=False,
        ),
    ]
