# Generated by Django 4.2.3 on 2024-04-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_tarjeta_cvv_remove_tarjeta_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='libro',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tarjeta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='biblioteca.tarjeta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tarjeta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='biblioteca.tarjeta'),
        ),
    ]
